### ISSUE TITLE
cleanup Encoding interface

### ISSUE THREAD

**Issue by vtolstov** [storj/drpc#13]
https://pkg.go.dev/storj.io/drpc#Encoding

can you remove JSONMarshal/JSONUnmarshal methods from Encoding interface? Not all proto encoders support json, and also this is really need only in gateway. so i'm suggest to drop this methods and on gateway side switch based on content-type and marshal/unmarshal to/from json via some other interface

**Comment by zeebo** [comment]
I also arrived at this conclusion, and it is done.

**Comment by vtolstov** [comment]
great
