### ISSUE TITLE
improve Error package

### ISSUE THREAD

**Issue by vtolstov** [storj/drpc#18]
i need to transfer error message from drpc server to drpc client, nor error type is not exportable. Do you plan to export Error type and ability to get error message ?
also it will be very useful to copy codes from grpc ( https://pkg.go.dev/google.golang.org/grpc/codes?utm_source=godoc ) via const to drpc

**Comment by zeebo** [comment]
Can you link exactly which error type you're referring to?

As far as copying the constants go, I didn't see the need for that to live in this repo. There's also many constants in there that don't apply (even gRPC doesn't use them!). I feel like for most people defining a couple of constants themselves is fine.

**Comment by vtolstov** [comment]
About error type i mean ability to transfer error message to client from drpc server.
About constants - i saw in you generated code that for unimplemented code 12 i think that the best way to create consts for error codes like for grpc and everybody who wants to be compatible to other drpc servers can use them.

**Comment by zeebo** [comment]
I think the message is propagated to the client. For example, I just wrote this test and added it to `internal/integration/error_test.go`:

```go
func TestError_Message(t *testing.T) {
	ctx := drpcctx.NewTracker(context.Background())
	defer ctx.Wait()
	defer ctx.Cancel()

	cli, close := createConnection(impl{
		Method1Fn: func(ctx context.Context, in *In) (*Out, error) {
			return nil, errors.New("some unique error message")
		},
	})
	defer close()

	out, err := cli.Method1(ctx, in(i))
	assert.Nil(t, out)
	assert.Error(t, err)
	assert.Equal(t, err.Error(), "some unique error message")
}
```

and it passed.

And yeah, adding 12 there is one of those "worse is better" situations. I wanted to pick some number so that it was identifiable. For me, any arbitrary number would have worked, so it might as well be the one gRPC picked. :shrug:

**Comment by zeebo** [comment]
Maybe just that specific constant could be added somewhere since it's being used. It doesn't really make sense to have it send out 12 without having users of the library able to know that.

**Comment by zeebo** [comment]
Since I like to do code reviews on Gerrit, I made

- https://review.dev.storj.io/c/storj/drpc/+/5040 adds that test
- https://review.dev.storj.io/c/storj/drpc/+/5041 adds and uses an Unimplemented constant

**Comment by vtolstov** [comment]
Thanks, but can you add other consts that used by grpc?
Some software akready used this codes and this will helpful to migration, also for me im use unauthenticated and other well known error codes.
So i think that this will not be bad thing

**Comment by zeebo** [comment]
The cost of committing to the exposed api surface by including all of the constants (including ones that gRPC doesn't use? why or why not?) outweighs for me the costs of requiring users to add at most 19 lines of code:

```go
const (
	OK                 = 0
	Canceled           = 1
	Unknown            = 2
	InvalidArgument    = 3
	DeadlineExceeded   = 4
	NotFound           = 5
	AlreadyExists      = 6
	PermissionDenied   = 7
	ResourceExhausted  = 8
	FailedPrecondition = 9
	Aborted            = 10
	OutOfRange         = 11
	Unimplemented      = 12
	Internal           = 13
	Unavailable        = 14
	DataLoss           = 15
	Unauthenticated    = 16
)
```

DRPC is its own library. If it doesn't make use of the codes, I don't think it should export them. That path leads to the api bloat that DRPC is trying to get away from.

**Comment by vtolstov** [comment]
What about adding only required and most used like

        OK                 = 0
	Canceled           = 1
	Unknown            = 2
	InvalidArgument    = 3
	DeadlineExceeded   = 4
	NotFound           = 5
	AlreadyExists      = 6
	PermissionDenied   = 7
	ResourceExhausted  = 8
	FailedPrecondition = 9
	Aborted            = 10
	Unimplemented      = 12
	Internal           = 13
	Unavailable        = 14
	Unauthenticated    = 16

**Comment by zeebo** [comment]
Even so, that's more API bloat that I don't want to have to maintain. The numbers aren't changing. They can live elsewhere.
