### ISSUE TITLE
Allow maximum payload size to be configurable

### ISSUE THREAD

**Issue by kylecarbs** [storj/drpc#29]
https://github.com/storj/drpc/blob/41e8fa5f513fe0893d3bef72310d0ccbba66cc74/drpcwire/reader.go#L119

It appears the maximum payload size is 4MB right now and isn't configurable. Is this an intentional design choice?

**Comment by vtolstov** [comment]
i think that this must be configured some option.

**Comment by zeebo** [comment]
I think it's fine to expose some options for this. The drpcmanager creates this type and already has an options struct exposed, so adding a NewReaderOptions seems reasonable.

**Comment by zeebo** [comment]
I'll try to do this monday, but I'm also happy to review any PRs :)

**Comment by kylecarbs** [comment]
Awesome- I'll toss one up, was just waiting for confirmation that it wasn't an intentional design choice to avoid!

**Comment by kylecarbs** [comment]
PR has been linked!

**Comment by kylecarbs** [comment]
https://github.com/storj/drpc/pull/31

This is _somewhat_ related. This error being hidden made it harder to debug.

**Comment by zeebo** [comment]
This is now implemented. Check out https://pkg.go.dev/storj.io/drpc@v0.0.32/drpcwire#ReaderOptions.

**Comment by kylecarbs** [comment]
Neato. Thank you @zeebo!
