### ISSUE TITLE
buffered Writer causes data races with net.Pipe

### ISSUE THREAD

**Issue by spikecurtis** [storj/drpc#33]
```
// Flush forces a flush of any buffered data to the io.Writer. It is a no-op if
// there is no data in the buffer.
func (b *Writer) Flush() (err error) {
	b.mu.Lock()
	if len(b.buf) > 0 {
		_, err = b.w.Write(b.buf)
		b.buf = b.buf[:0]
		atomic.StoreUint32(&b.empty, 0)
	}
	b.mu.Unlock()
	return err
}
```

The underlying assumption with this code is that `Write()` synchronously copies the data out of the buffer, such that it is safe to truncate the buffer to keep using it.  This is unfortunately not the case with `net.Pipe`, which does the copy on the goroutine that reads from the pipe, and is thus asynchronous.

We're hitting these issues internally, as we do some internal comms over `net.Pipe` such that those internal comms use the same code as real networked communications.

Would you be willing to accept a patch?

**Comment by zeebo** [comment]
Are you certain the problem is `net.Pipe`? If so, that sounds like a bug with the standard library. The [documentation for io.Writer](https://pkg.go.dev/io#Writer) states

> Implementations must not retain p. 

Can you provide a reproducer for the issue?

**Comment by spikecurtis** [comment]
Thanks!, I missed that part of the io.Writer docs.  I've been chasing this down more, and I think `net.Pipe` is fine in this regard, but actually another part of our stack can retain the pointer after returning from `Write()`.

Sorry for the noise.
