### ISSUE TITLE
Support for custom codec?

### ISSUE THREAD

**Issue by ccnlui** [storj/drpc#34]
Is there any support for using other codec other than protobufs? How would you implement a server using a custom codec?

**Comment by zeebo** [comment]
Yep, that's what the [Encoding](https://pkg.go.dev/storj.io/drpc#Encoding) type is supposed to abstract. 

The code generator still requires a proto service definition and message types, but you can use the `protolib` option to specify an import path ([for example](https://github.com/storj/drpc/blob/main/internal/integration/doc.go#L9), this specifies the import path of `storj.io/drpc/internal/integration/customencoding`) to a package that contains top level `Marshal` and `Unmarshal` functions ([for example](https://github.com/storj/drpc/blob/main/internal/integration/customencoding/customencoding.go), this just dispatches to protobuf again, but you can do whatever you want here).

Do you have a specific encoding you want to use? I can try to figure out some more of the details if you have a concrete encoding in mind already.

**Comment by ccnlui** [comment]
Thanks for the tips.
I'm thinking of using flatbuffers with drpc, if that's possible.

**Comment by santakdalai90** [comment]
> Thanks for the tips. I'm thinking of using flatbuffers with drpc, if that's possible.

were you able to try it? please share the documentation, if you've created any. Thanks
