### ISSUE TITLE
What is the max message size handling approach?

### ISSUE THREAD

**Issue by newhook** [storj/drpc#39]
grpc has `grpc.MaxRecvMsgSize` and `grpc.MaxSendMsgSize` which restrict the maximum amount of data which can be sent or received by a grpc client/server. 

What is the strategy that drpc uses? I did some tests with sending large amounts of data with the defaults. 1024 * 1024 bytes works fine. 1024 * 1024 * 100 bytes causes a `data overflow` protocol error from the server.

Looking at the code I can see some various
```
type ReaderOptions struct {
	// MaximumBufferSize controls the maximum size of buffered
	// packet data.
	MaximumBufferSize int
}
```

and

```
// Options controls configuration settings for a stream.
type Options struct {
	// SplitSize controls the default size we split packets into frames.
	SplitSize int

	// ManualFlush controls if the stream will automatically flush after every
	// message send. Note that flushing is not part of the drpc.Stream
	// interface, so if you use this you must be ready to type assert and
	// call RawFlush dynamically.
	ManualFlush bool

	// MaximumBufferSize causes the Stream to drop any internal buffers that
	// are larger than this amount to control maximum memory usage at the
	// expense of more allocations. 0 is unlimited.
	MaximumBufferSize int

	// Internal contains options that are for internal use only.
	Internal drpcopts.Stream
}
```

However, it isn't really clear the strategy or what I should be setting. Can anyone help here?

**Comment by zeebo** [comment]
The stream options control only optimization details. The current limit is 4 MiB, and that's controlled by the ReaderOptions.MaximumBufferSize, as you found.

For example:

```go
drpcconn.NewWithOptions(tr, drpcconn.Options{
	Manager: drpcmanager.Options{
		Reader: drpcwire.ReaderOptions{
			MaximumBufferSize: 1024 * 1024,
		},
	},
})
```

**Comment by zeebo** [comment]
Yeah, there's currently options to limit the size of the sent data. That seems like it should be an easy addition to the drpcstream options, though. Is that a needed feature for you?

**Comment by newhook** [comment]
Did you mean limit the size of received data?

I don't think we need an option to limit sent data. A bad client might send a rejected request, that seems to be the worst case.

**Comment by zeebo** [comment]
You asked

>  Is there a corresponding parameter to control how much data will be written to a connection?

which I interpreted as limiting the size of the data you're going to send. I think we're talking past each other :smile:.

You can limit the client read buffer size by using drpcconn.NewWithOptions, and you can limit the server read buffer size by using drpcserver.NewWithOptions (they both have a drpcmanager.Options field on their options struct). That covers both the client and servers protecting the amount they will read, but not how much either will write.

**Comment by newhook** [comment]
lol, I think we're on the same page. Thanks for clarifying things.
