### ISSUE TITLE
Support for Interceptors/Middleware?

### ISSUE THREAD

**Issue by pigfrown** [storj/drpc#4]
Does dRPC support Interceptors? If not, how can I implement middleware for a dRPC server?

Thanks

**Comment by pigfrown** [comment]
I looked through the storj code that uses drpc and saw that rpctracing is implemented by using Handlers, which seem to be equivalent to gRPC interceptors, and this approach allowed me to add my own middleware to a dRPC server.

However I can't find an example that shows how I can achieve the same thing on the client side. Is this possible in dRPC?

Thanks

**Comment by zeebo** [comment]
You should be able to wrap the drpc.Conn type that you pass to create the client. Does that work for your situation?

The intent is that all the primitives can be composed or wrapped closer to something like net/http. 

Let me know if this doesn't work or if it can be made easier.

**Comment by jtolio** [comment]
Please re-open if the above approach didn't take care of your needs!

**Comment by BRUHItsABunny** [comment]
So if I understand this correctly in order to do authentication on my http handler I should wrap the drpc's http handler into a new struct with it's own ServerHTTP func and essentially do the checking there and then call drpc's ServeHTTP?

**Comment by Erikvv** [comment]
That would work, if indeed your authentication works on the HTTP layer, like through a HTTP request header.
