### ISSUE TITLE
Client load balancing

### ISSUE THREAD

**Issue by jashakimov** [storj/drpc#49]
How I can change the client with resolver with list of sockets ? 

Like original grpc.Dial(..., grpc.WithLoadBalancer(roundRobin))

**Comment by zeebo** [comment]
There's no special code to do client side load balancing in the repo. 

That said, this should be possible to do externally in the same sort of way connection pooling can be 3rd party like [go.bryk.io/pkg/net/drpc](https://pkg.go.dev/go.bryk.io/pkg/net/drpc) and [go.arsenm.dev/drpc](https://pkg.go.dev/go.arsenm.dev/drpc). If you write the package, I'll gladly link it in the README.
