### ISSUE TITLE
What does the "D" stand for? 

### ISSUE THREAD

**Issue by okb1100** [storj/drpc#51]
I was going through the documentation and blog posts but couldn't find any answer about the question; what does the "D" mean in DRPC? 

Thanks

**Comment by cristaloleg** [comment]
I bet for 'decentralized'.

**Comment by zeebo** [comment]
Here's a copy of a comment I made answering this question on the reddit submission for the blog post:

> I think the official answer is "Distributed" or something equally businessey. In my heart, it will always mean "Dumb" or "Doomed" and the acronym is pronounced "derpsy". The real answer is that it stands for the friends we made along the way.
