### ISSUE TITLE
graceful shutdown and handler timeout

### ISSUE THREAD

**Issue by vtolstov** [storj/drpc#9]
i'm maintain a fork of go-micro ( github.com/unistack-org/micro ) and want to add drpc client/server support to it.
grpc does not have native ability to pass context to server and also does not allow adding handler timeouts easy (via context with timeout or something like this)
What you think about graceful shutdown of dprc handlers ? Do you plan to add option for server to specify handler timeout?

**Comment by zeebo** [comment]
Can you propose an API for what that might look like for servers?

**Comment by vtolstov** [comment]
may be like this https://golang.org/pkg/net/http/#Server.Shutdown ?

**Comment by zeebo** [comment]
Canceling the context passed in to https://github.com/storj/drpc/blob/main/drpcserver/server.go#L68 will cancel any ongoing streams, close the listener, and wait for them to exit. Is that sufficient?

**Comment by vtolstov** [comment]
Yeah, looks ok.
